### ISSUE TITLE
Problem with loading data (SEM array tomography tile set array)

### ISSUE THREAD

**Issue by severiku** [PreibischLab/BigStitcher#101]
Hello, 
first time user of Big Stitcher with the following problem.
I can not load my Array Tomography (SEM) data set with 6x15 tiles, 21 sections (11GB).

Naming of files (output from the microscope): Tile_001-001-000018_0-000.s0019_e01
Explanation: Tile_001-[tile in x]_001-[tile in y]_000018-[section19, starts with 0]_0-000[detector]_.s0019[section]_e01[energy, can be ignored]

When loading the tile set from one section I have no problems. When loading the whole data set, this appears:
[Tue Aug 17 15:47:25 CEST 2021] [ERROR] [] Module threw exception
java.lang.IllegalStateException: net.preibisch.mvrecon.fiji.spimdata.imgloaders.LegacyFileMapImgLoaderLOCI.lambda$checkAndRemoveZeroVolume$3: Current file should not be null; call setId(String) first
	at loci.formats.FormatTools.assertId(FormatTools.java:988)
	at loci.formats.FileStitcher.setSeries(FileStitcher.java:568)
	at net.preibisch.mvrecon.fiji.spimdata.imgloaders.LegacyFileMapImgLoaderLOCI.lambda$checkAndRemoveZeroVolume$3(LegacyFileMapImgLoaderLOCI.java:492)
	at java.util.HashMap$EntrySet.forEach(Unknown Source)
	at net.preibisch.mvrecon.fiji.spimdata.imgloaders.LegacyFileMapImgLoaderLOCI.checkAndRemoveZeroVolume(LegacyFileMapImgLoaderLOCI.java:472)
	at net.preibisch.mvrecon.fiji.datasetmanager.FileListDatasetDefinition.createDataset(FileListDatasetDefinition.java:1088)
	at net.preibisch.mvrecon.fiji.plugin.Define_Multi_View_Dataset.defineDataset(Define_Multi_View_Dataset.java:142)
	at net.preibisch.mvrecon.fiji.plugin.queryXML.LoadParseQueryXML.queryXML(LoadParseQueryXML.java:122)
	at net.preibisch.mvrecon.fiji.plugin.queryXML.LoadParseQueryXML.queryXML(LoadParseQueryXML.java:109)
	at net.preibisch.stitcher.plugin.BigStitcher.run(BigStitcher.java:73)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
[Tue Aug 17 16:13:04 CEST 2021] [ERROR] [] Module threw exception
java.lang.RuntimeException: Could not load 'H:\PC_MDC_Daten\AT\E435_non-stroke\Tile_01-001-0000<00>_0-000.s001_e01.tif' viewId=0, tpId=0: java.io.FileNotFoundException: H:\PC_MDC_Daten\AT\E435_non-stroke\Tile_01-001-000000_0-000.s001_e01.tif (Das System kann die angegebene Datei nicht finden)
	at net.preibisch.mvrecon.fiji.spimdata.imgloaders.LegacyFileMapImgLoaderLOCI.getImage(LegacyFileMapImgLoaderLOCI.java:169)
	at mpicbg.spim.data.legacy.LegacyImgLoaderWrapper$SetupImgLoaderWrapper.getImage(LegacyImgLoaderWrapper.java:79)
	at bdv.export.WriteSequenceToHdf5.writeHdf5PartitionFile(WriteSequenceToHdf5.java:445)
	at bdv.export.WriteSequenceToHdf5.writeHdf5File(WriteSequenceToHdf5.java:152)
	at net.preibisch.mvrecon.fiji.plugin.resave.Generic_Resave_HDF5.writeHDF5(Generic_Resave_HDF5.java:261)
	at net.preibisch.mvrecon.fiji.datasetmanager.FileListDatasetDefinition.createDataset(FileListDatasetDefinition.java:1154)
	at net.preibisch.mvrecon.fiji.plugin.Define_Multi_View_Dataset.defineDataset(Define_Multi_View_Dataset.java:142)
	at net.preibisch.mvrecon.fiji.plugin.queryXML.LoadParseQueryXML.queryXML(LoadParseQueryXML.java:122)
	at net.preibisch.mvrecon.fiji.plugin.queryXML.LoadParseQueryXML.queryXML(LoadParseQueryXML.java:109)
	at net.preibisch.stitcher.plugin.BigStitcher.run(BigStitcher.java:73)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source) 

All the best,
Séverine

**Comment by Eddymorphling** [comment]
Hi @severiku I have been recently trying to do the same task with AT-SEM datasets and Bigstitcher.  I came across the same error. Were you able to find a fix for this?

**Comment by severiku** [comment]
Dear Praveen,

No, I have no fix. I used another software solution.
There is a Windows Programm ICE which works quite nicely (works on windows 10).
Maybe some people from Thermo Fisher might have some ideas how to rename the files so they are compatible with Big Stitcher....

Best wishes, please keep me updated if you find something useful.

Séverine


Am 13.02.2023 18:53 schrieb Praveen ***@***.***>:

Hi @severiku<https://github.com/severiku> I have been recently trying to do the same task with AT-SEM datasets and Bigstitcher. I came across the same error. Were you able to find a fix for this?
