### ISSUE TITLE
Split images raising 

### ISSUE THREAD

**Issue by boazmohar** [PreibischLab/BigStitcher#109]
When using `Plugins\BigStitcher\Tools\SplitImages` my XML file that was made with [pybdv](https://github.com/constantinpape/pybdv) is raising the following:
```bash
(Fiji Is Just) ImageJ 2.3.0/1.53f51; Java 1.8.0_172 [64-bit]; Linux 4.18.0-305.3.1.el8_4.x86_64; 27418MB of 573233MB (4%)
 
java.lang.NullPointerException
	at net.preibisch.mvrecon.process.splitting.SplittingTools.splitImages(SplittingTools.java:166)
	at net.preibisch.mvrecon.fiji.plugin.Split_Views.split(Split_Views.java:85)
	at net.preibisch.mvrecon.fiji.plugin.Split_Views.split(Split_Views.java:154)
	at net.preibisch.mvrecon.fiji.plugin.Split_Views.run(Split_Views.java:71)
	at ij.IJ.runUserPlugIn(IJ.java:241)
	at ij.IJ.runPlugIn(IJ.java:204)
	at ij.Executer.runCommand(Executer.java:150)
	at ij.Executer.run(Executer.java:68)
	at java.lang.Thread.run(Thread.java:748)
```

Attached is the xml file as zip.
[C4_IHC3_v4_orig.zip](https://github.com/PreibischLab/BigStitcher/files/7627755/C4_IHC3_v4_orig.zip)

Any advice?
@StephanPreibisch

**Comment by StephanPreibisch** [comment]
I suspect that the XML file was not written by BigStitcher but some other software, is that possible? There are some elements missing ... in any case, it should be fixed with the above commit. Now releasing 0.11.5 ...
