### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by AdvancedImagingUTSW** [PreibischLab/BigStitcher#120]
Hello Everyone,

I recently ran into an issue that I never experienced before.  Running on a Linux machine. 367GB of RAM. While trying to figure out the cause, I updated ImageJ, and removed and reinstalled BigStitcher. I am trying to stitch a file that is in the N5 format. 

So far, pairwise phase correlation continues to fail. Attempted it on multiple datasets. Other features, such as image fusion, seem to work perfectly. It seems as if a single method is missing...

I appreciate the help,
Kevin

## Log Output
```
Tue Feb 21 13:23:06 CST 2023: Removed 18180 non-overlapping view-pairs for computing.
Computing overlap for: 12 pairs of images at once, each 6 threads, (in total <=72 threads)
Total num CPUs: 72
Failed to compute pairwise shift: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.preibisch.mvrecon.process.downsampling.DownsampleTools.openAndDownsample(Lmpicbg/spim/data/generic/sequence/BasicImgLoader;Lmpicbg/spim/data/sequence/ViewId;Lnet/imglib2/realtransform/AffineTransform3D;[JZZ)Lnet/imglib2/RandomAccessibleInterval;
```

## Console Output
```
...
non translations equal
non translations equal
non translations equal
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.preibisch.mvrecon.process.downsampling.DownsampleTools.openAndDownsample(Lmpicbg/spim/data/generic/sequence/BasicImgLoader;Lmpicbg/spim/data/sequence/ViewId;Lnet/imglib2/realtransform/AffineTransform3D;[JZZ)Lnet/imglib2/RandomAccessibleInterval;
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.preibisch.stitcher.algorithm.globalopt.TransformationTools.computePairs(TransformationTools.java:639)
	at net.preibisch.stitcher.plugin.Calculate_Pairwise_Shifts.processPhaseCorrelation(Calculate_Pairwise_Shifts.java:179)
	at net.preibisch.stitcher.gui.popup.CalculatePCPopup$MyActionListener$1.run(CalculatePCPopup.java:179)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: net.preibisch.mvrecon.process.downsampling.DownsampleTools.openAndDownsample(Lmpicbg/spim/data/generic/sequence/BasicImgLoader;Lmpicbg/spim/data/sequence/ViewId;Lnet/imglib2/realtransform/AffineTransform3D;[JZZ)Lnet/imglib2/RandomAccessibleInterval;
	at net.preibisch.stitcher.algorithm.GroupedViewAggregator.aggregate(GroupedViewAggregator.java:381)
	at net.preibisch.stitcher.algorithm.globalopt.TransformationTools.computeStitching(TransformationTools.java:271)
	at net.preibisch.stitcher.algorithm.globalopt.TransformationTools$2.call(TransformationTools.java:586)
	at net.preibisch.stitcher.algorithm.globalopt.TransformationTools$2.call(TransformationTools.java:568)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Exception in thread "Thread-100" java.lang.NullPointerException
	at net.preibisch.stitcher.plugin.Calculate_Pairwise_Shifts.processPhaseCorrelation(Calculate_Pairwise_Shifts.java:201)
	at net.preibisch.stitcher.gui.popup.CalculatePCPopup$MyActionListener$1.run(CalculatePCPopup.java:179)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by StephanPreibisch** [comment]
Hi, it should be fixed now @AdvancedImagingUTSW, could you please try after updating Fiji? Thanks so much for reporting!!!

**Comment by AdvancedImagingUTSW** [comment]
Hey @StephanPreibisch,

Thanks for the quick fix.  It looks like it is now running perfectly again!

Have a great day!

Kevin

PS. Would love to chat sometime about some of your latest work with stage scanning acquisitions that require shearing.

**Comment by StephanPreibisch** [comment]
absolutely, next week maybe?

**Comment by AdvancedImagingUTSW** [comment]
That would be great. I'll shoot you an e-mail.
