### ISSUE TITLE
Error loading tiffs

### ISSUE THREAD

**Issue by smith6jt-cop** [PreibischLab/BigStitcher#135]
Hello,

Using most recent FIJI, Bioformats, BigStitcher, on Windows10.  Tried both automatic and manual loader to load multiplex tiffs with format \Z={tt}C={c}\00{xx}.tif (tried experimental z-stack loading with auto loader and z as timepoints with manual).  Manual loader error:

(Fiji Is Just) ImageJ 2.14.0/1.54f; Java 1.8.0_322 [64-bit]; Windows 10 10.0; 359MB of 48726MB (<1%)
 
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:308)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:166)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:152)
	at ij.Executer.run(Executer.java:70)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:304)
	... 5 more
Caused by: java.lang.RuntimeException: Module threw exception
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:128)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: java.lang.NullPointerException
	at net.preibisch.mvrecon.fiji.spimdata.imgloaders.LegacyStackImgLoaderIJ.open(LegacyStackImgLoaderIJ.java:70)
	at net.preibisch.mvrecon.fiji.spimdata.imgloaders.LegacyStackImgLoaderIJ.loadMetaData(LegacyStackImgLoaderIJ.java:230)
	at net.preibisch.mvrecon.fiji.spimdata.imgloaders.AbstractImgLoader.getImageSize(AbstractImgLoader.java:80)
	at mpicbg.spim.data.legacy.LegacyImgLoaderWrapper$SetupImgLoaderWrapper.getImageSize(LegacyImgLoaderWrapper.java:97)
	at net.preibisch.mvrecon.fiji.datasetmanager.StackList.createDataset(StackList.java:314)
	at net.preibisch.mvrecon.fiji.plugin.Define_Multi_View_Dataset.defineDataset(Define_Multi_View_Dataset.java:142)
	at net.preibisch.mvrecon.fiji.plugin.queryXML.LoadParseQueryXML.queryXML(LoadParseQueryXML.java:122)
	at net.preibisch.mvrecon.fiji.plugin.queryXML.LoadParseQueryXML.queryXML(LoadParseQueryXML.java:109)
	at net.preibisch.stitcher.plugin.BigStitcher.run(BigStitcher.java:73)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	... 6 more

**Comment by smith6jt-cop** [comment]
Fresh install of FIJI fixed issue
