### ISSUE TITLE
Intensity adjustment superslow

### ISSUE THREAD

**Issue by jbogomolovas2** [PreibischLab/BigStitcher#139]
First of all, Bigstitcher is amazing for Lightsheet data processing. All needed functions even without GPU support are super-efficient for 20-30 GB; 1-2 channel, 4-5 angle datasets I am working, except for intensity adjustment, which I found to be quite useful. Basically, it either is super slow (I am getting result in 5-6 hours) or it crashes Fiji.
I use fiji v.1.54j, spimdata version: 0.9-revision; multiview-reconstruction version: 3.3.0, on Windows 10 Pro operating system.

So in active phase of Intensity adjustment, when CPU is buzzing and RAMs are filling up I get this:

Thread-25" prio=6 id=135 group=main
   java.lang.Thread.State: RUNNABLE
	at net.imglib2.img.cell.CellRandomAccess.setPosition(CellRandomAccess.java:393)
	at net.imglib2.converter.AbstractConvertedRandomAccess.setPosition(AbstractConvertedRandomAccess.java:164)
	at net.imglib2.position.transform.Floor.setPosition(Floor.java:191)
	at net.preibisch.mvrecon.process.fusion.transformed.TransformedInputRandomAccess.get(TransformedInputRandomAccess.java:74)
	at net.preibisch.mvrecon.process.fusion.transformed.TransformedInputRandomAccess.get(TransformedInputRandomAccess.java:39)
	at net.preibisch.mvrecon.process.fusion.intensityadjust.IntensityAdjustmentTools.computeIntensityAdjustment(IntensityAdjustmentTools.java:152)
	at net.preibisch.mvrecon.fiji.plugin.Intensity_Adjustment.intensityAdjustment(Intensity_Adjustment.java:190)
	at net.preibisch.mvrecon.fiji.plugin.Intensity_Adjustment.intensityAdjustment(Intensity_Adjustment.java:93)
	at net.preibisch.mvrecon.fiji.spimdata.explorer.popup.IntensityAdjustmentPopup$MyActionListener$1.run(IntensityAdjustmentPopup.java:108)
	at java.lang.Thread.run(Thread.java:750)

In silent phase when CPU is quiet, but RAM remains filled to estimated volume, I  am getting this:

Thread-25" prio=6 id=135 group=main
   java.lang.Thread.State: RUNNABLE
	at net.preibisch.mvrecon.process.fusion.intensityadjust.IntensityAdjustmentTools.computeIntensityAdjustment(IntensityAdjustmentTools.java:172)
	at net.preibisch.mvrecon.fiji.plugin.Intensity_Adjustment.intensityAdjustment(Intensity_Adjustment.java:190)
	at net.preibisch.mvrecon.fiji.plugin.Intensity_Adjustment.intensityAdjustment(Intensity_Adjustment.java:93)
	at net.preibisch.mvrecon.fiji.spimdata.explorer.popup.IntensityAdjustmentPopup$MyActionListener$1.run(IntensityAdjustmentPopup.java:108)
	at java.lang.Thread.run(Thread.java:750)

Any insights to make Intensity adjustment work would be highly appreciated.
Regards,
Julius

**Comment by jbogomolovas2** [comment]
Turned out I need to down-sample more than 10X
