### ISSUE TITLE
Iterative Global Opt crashes sometimes

### ISSUE THREAD

**Issue by StephanPreibisch** [PreibischLab/BigStitcher#15]
Optimizing...
Shuffling took 0 ms
First apply took 1 ms
resetting savedFilteringAndGrouping
Exception in thread "Thread-335" java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: mpicbg.models.NotEnoughDataPointsException: 0 data points are not enough to estimate a 3d translation model, at least 1 data points required.
	at mpicbg.models.TileConfiguration.optimize(TileConfiguration.java:358)
	at mpicbg.models.TileConfiguration.optimize(TileConfiguration.java:310)
	at mpicbg.models.TileConfiguration.optimize(TileConfiguration.java:328)
	at net.preibisch.mvrecon.process.interestpointregistration.global.GlobalOptIterative.compute(GlobalOptIterative.java:98)
	at net.preibisch.mvrecon.process.interestpointregistration.global.GlobalOptTwoRound.compute(GlobalOptTwoRound.java:111)
	at net.preibisch.stitcher.algorithm.globalopt.GlobalOptStitcher.processGlobalOptimization(GlobalOptStitcher.java:171)
	at net.preibisch.stitcher.algorithm.globalopt.ExecuteGlobalOpt.run(ExecuteGlobalOpt.java:107)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: mpicbg.models.NotEnoughDataPointsException: 0 data points are not enough to estimate a 3d translation model, at least 1 data points required.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at mpicbg.models.TileUtil.optimizeConcurrently(TileUtil.java:219)
	at mpicbg.models.TileConfiguration.optimizeSilentlyConcurrent(TileConfiguration.java:288)
	at mpicbg.models.TileConfiguration.optimize(TileConfiguration.java:354)
	... 7 more
Caused by: java.lang.RuntimeException: mpicbg.models.NotEnoughDataPointsException: 0 data points are not enough to estimate a 3d translation model, at least 1 data points required.
	at mpicbg.models.TileUtil$3.run(TileUtil.java:206)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 more
Caused by: mpicbg.models.NotEnoughDataPointsException: 0 data points are not enough to estimate a 3d translation model, at least 1 data points required.
	at mpicbg.models.TranslationModel3D.fit(TranslationModel3D.java:89)
	at mpicbg.models.Tile.fitModel(Tile.java:315)
	at mpicbg.models.TileUtil$3.run(TileUtil.java:200)
	... 5 more

**Comment by StephanPreibisch** [comment]
fixed with https://github.com/PreibischLab/multiview-reconstruction/commit/d10ffd023fa050c36b1215626cc0f31a6993c43d

**Comment by StephanPreibisch** [comment]
@iarganda @frusak
