### ISSUE TITLE
CMD+a creates an exception on Mac

### ISSUE THREAD

**Issue by StephanJanosch** [PreibischLab/BigStitcher#22]
latest updates installed:

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at net.preibisch.stitcher.gui.bdv.BDVFlyThrough.addCurrentViewerTransform(BDVFlyThrough.java:31)
	at net.preibisch.stitcher.gui.StitchingExplorerPanel$12.keyPressed(StitchingExplorerPanel.java:1147)
	at java.awt.AWTEventMulticaster.keyPressed(AWTEventMulticaster.java:250)
	at java.awt.Component.processKeyEvent(Component.java:6497)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2832)
	at java.awt.Component.processEvent(Component.java:6316)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:835)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1103)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:974)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:800)
	at java.awt.Component.dispatchEventImpl(Component.java:4760)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

repro: create a new dataset with BS on MacOS 10.11 and simply press CMD+A

**Comment by hoerldavid** [comment]
Hi @StephanJanosch,

This was caused by an "easter-egg" BigDataViewer movie recording mode we added in 64376da6. 
* Pressing ```a``` will add a keyframe to the recording
* ```x``` will discard the keyframes
* ```s``` will start the recording.

We did not check if BDV is not null and this caused the exception.

Since 959182ed17ab4cc0cecf34484b0f6c677e8ebf11, you are required to press ```E``` before entering the recording mode.

The Exception might still occur if you enter recording mode but do not have the BigDataViewer open as you press ```a``` (or ```s```), so I added an extra safeguard with cf12ebe7b7639d7bb985d115ab95ad040e36b08a. This should take care of this problem.

Best,
David
