### ISSUE TITLE
reserving to HDF5 does not work on windows 7

### ISSUE THREAD

**Issue by StephanJanosch** [PreibischLab/BigStitcher#23]
```
Exception in thread "Thread-10" java.lang.NullPointerException
	at mpicbg.spim.data.XmlHelpers.pathElement(XmlHelpers.java:321)
	at mpicbg.spim.data.generic.XmlIoAbstractSpimData.toXml(XmlIoAbstractSpimData.java:183)
	at net.preibisch.mvrecon.fiji.spimdata.XmlIoSpimData2.toXml(XmlIoSpimData2.java:218)
	at net.preibisch.mvrecon.fiji.spimdata.XmlIoSpimData2.toXml(XmlIoSpimData2.java:52)
	at mpicbg.spim.data.generic.XmlIoAbstractSpimData.save(XmlIoAbstractSpimData.java:101)
	at net.preibisch.mvrecon.fiji.spimdata.XmlIoSpimData2.save(XmlIoSpimData2.java:131)
	at net.preibisch.mvrecon.fiji.spimdata.XmlIoSpimData2.save(XmlIoSpimData2.java:52)
	at net.preibisch.stitcher.gui.StitchingExplorerPanel.saveXML(StitchingExplorerPanel.java:1093)
	at net.preibisch.mvrecon.fiji.spimdata.explorer.popup.ResavePopup$MyActionListener$1.run(ResavePopup.java:212)
	at java.lang.Thread.run(Thread.java:748)
```

Repro: Create a Dataset from TIFs on Windows 7 and resave it to HDF5.

**Comment by StephanJanosch** [comment]
same error get's triggered when saving after stitching assistant:

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at mpicbg.spim.data.XmlHelpers.pathElement(XmlHelpers.java:321)
	at mpicbg.spim.data.generic.XmlIoAbstractSpimData.toXml(XmlIoAbstractSpimData.java:183)
	at net.preibisch.mvrecon.fiji.spimdata.XmlIoSpimData2.toXml(XmlIoSpimData2.java:218)
	at net.preibisch.mvrecon.fiji.spimdata.XmlIoSpimData2.toXml(XmlIoSpimData2.java:52)
	at mpicbg.spim.data.generic.XmlIoAbstractSpimData.save(XmlIoAbstractSpimData.java:101)
	at net.preibisch.mvrecon.fiji.spimdata.XmlIoSpimData2.save(XmlIoSpimData2.java:131)
	at net.preibisch.mvrecon.fiji.spimdata.XmlIoSpimData2.save(XmlIoSpimData2.java:52)
	at net.preibisch.stitcher.gui.StitchingExplorerPanel.saveXML(StitchingExplorerPanel.java:1093)
	at net.preibisch.stitcher.gui.StitchingExplorerPanel$4.actionPerformed(StitchingExplorerPanel.java:530)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
Cannot provide XML file as it does not save ;-)

**Comment by StephanPreibisch** [comment]
Hi, we will have a look, but it’s Windows 7 is most likely not the reason ... most likely it has something to do with your files, can you share them too maybe?

**Comment by StephanPreibisch** [comment]
Hi again, these error seem very weird and I cannot reproduce them, can you please upload some screenshots of how you get to these errors (and maybe a small set of the data to reproduce the error)? Also, we recommend using the AutoLoader for importing instead of the verbose Manual Loader - but that's more for your convenience ...

**Comment by StephanJanosch** [comment]
I could trigger the behaviour repeatedly. I created a dataset with windows and it reserved to hdf5 just fine. Then I stitched **only 6** out of 8 views and wanted to save. 
Exception:
```Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at mpicbg.spim.data.XmlHelpers.pathElement(XmlHelpers.java:321)
	at mpicbg.spim.data.generic.XmlIoAbstractSpimData.toXml(XmlIoAbstractSpimData.java:183)
	at net.preibisch.mvrecon.fiji.spimdata.XmlIoSpimData2.toXml(XmlIoSpimData2.java:218)
	at net.preibisch.mvrecon.fiji.spimdata.XmlIoSpimData2.toXml(XmlIoSpimData2.java:52)
	at mpicbg.spim.data.generic.XmlIoAbstractSpimData.save(XmlIoAbstractSpimData.java:101)
	at net.preibisch.mvrecon.fiji.spimdata.XmlIoSpimData2.save(XmlIoSpimData2.java:131)
	at net.preibisch.mvrecon.fiji.spimdata.XmlIoSpimData2.save(XmlIoSpimData2.java:52)
	at net.preibisch.stitcher.gui.StitchingExplorerPanel.saveXML(StitchingExplorerPanel.java:1093)
	at net.preibisch.stitcher.gui.StitchingExplorerPanel$4.actionPerformed(StitchingExplorerPanel.java:530)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
Windows Video: https://cloud.mpi-cbg.de/index.php/s/lb1xkivlZFxOrsO

And on the mac it works just fine. I Start out with with 6 out of 8 views. Stitch them and save them. Then I stitch the 2 remaining ones and move them by hand into position.

Mac Video: https://cloud.mpi-cbg.de/index.php/s/SHUvwEWZAlv36oa
