### ISSUE TITLE
NoSuchElementException with automatic loader

### ISSUE THREAD

**Issue by StephanJanosch** [PreibischLab/BigStitcher#24]
Happens on Windows and Linux.

Dataset: https://cloud.mpi-cbg.de/index.php/s/gfv7HhpXhAQlaTK

Console:

```Including file \\fileserver.mpi-cbg.de\SarovHFSP\2018-07-19_steph\nip2-gfp_his72-mCh_his58_mCh_TRG_1668\Worm5_L3\nip2-gfp_his72-mCh_his58-mCh.tif in dataset.
Including file \\fileserver.mpi-cbg.de\SarovHFSP\2018-07-19_steph\nip2-gfp_his72-mCh_his58_mCh_TRG_1668\Worm5_L3\nip2-gfp_his72-mCh_his58-mCh1.tif in dataset.
Including file \\fileserver.mpi-cbg.de\SarovHFSP\2018-07-19_steph\nip2-gfp_his72-mCh_his58_mCh_TRG_1668\Worm5_L3\nip2-gfp_his72-mCh_his58-mCh2.tif in dataset.
Including file \\fileserver.mpi-cbg.de\SarovHFSP\2018-07-19_steph\nip2-gfp_his72-mCh_his58_mCh_TRG_1668\Worm5_L3\nip2-gfp_his72-mCh_his58-mCh3.tif in dataset.
Including file \\fileserver.mpi-cbg.de\SarovHFSP\2018-07-19_steph\nip2-gfp_his72-mCh_his58_mCh_TRG_1668\Worm5_L3\nip2-gfp_his72-mCh_his58-mCh4.tif in dataset.
FluoviewReader initializing \\fileserver.mpi-cbg.de\SarovHFSP\2018-07-19_steph\nip2-gfp_his72-mCh_his58_mCh_TRG_1668\Worm5_L3\nip2-gfp_his72-mCh_his58-mCh.tif
Reading IFDs
Populating metadata
Populating OME metadata
FluoviewReader initializing \\fileserver.mpi-cbg.de\SarovHFSP\2018-07-19_steph\nip2-gfp_his72-mCh_his58_mCh_TRG_1668\Worm5_L3\nip2-gfp_his72-mCh_his58-mCh1.tif
Reading IFDs
Populating metadata
Populating OME metadata
FluoviewReader initializing \\fileserver.mpi-cbg.de\SarovHFSP\2018-07-19_steph\nip2-gfp_his72-mCh_his58_mCh_TRG_1668\Worm5_L3\nip2-gfp_his72-mCh_his58-mCh2.tif
Reading IFDs
Populating metadata
Populating OME metadata
FluoviewReader initializing \\fileserver.mpi-cbg.de\SarovHFSP\2018-07-19_steph\nip2-gfp_his72-mCh_his58_mCh_TRG_1668\Worm5_L3\nip2-gfp_his72-mCh_his58-mCh3.tif
Reading IFDs
Populating metadata
Populating OME metadata
FluoviewReader initializing \\fileserver.mpi-cbg.de\SarovHFSP\2018-07-19_steph\nip2-gfp_his72-mCh_his58_mCh_TRG_1668\Worm5_L3\nip2-gfp_his72-mCh_his58-mCh4.tif
Reading IFDs
Populating metadata
Populating OME metadata
VS: 0
Error: more than one View: ch0 a0 ti0 tp0 i0
VS: 0
Error: more than one View: ch1 a0 ti0 tp0 i0
VS: 0
Error: more than one View: ch2 a0 ti0 tp0 i0
true
[ERROR] Module threw exception
java.util.NoSuchElementException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1444)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1466)
	at net.preibisch.mvrecon.fiji.datasetmanager.FileListDatasetDefinition.createDataset(FileListDatasetDefinition.java:952)
	at net.preibisch.mvrecon.fiji.plugin.Define_Multi_View_Dataset.defineDataset(Define_Multi_View_Dataset.java:141)
	at net.preibisch.mvrecon.fiji.plugin.queryXML.LoadParseQueryXML.queryXML(LoadParseQueryXML.java:122)
	at net.preibisch.mvrecon.fiji.plugin.queryXML.LoadParseQueryXML.queryXML(LoadParseQueryXML.java:109)
	at net.preibisch.stitcher.plugin.BigStitcher.run(BigStitcher.java:74)
	at org.scijava.command.CommandModule.run(CommandModule.java:199)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
Fiji and Files
![win_bug_1_1](https://user-images.githubusercontent.com/11651596/43074825-e341fffc-8e7e-11e8-8ee5-fca29b14c43a.png)
proper files found
![win_bug_1_2](https://user-images.githubusercontent.com/11651596/43074828-e51e922c-8e7e-11e8-85d1-77584c0a5ffe.png)
metadata looks good 
![win_bug_1_3](https://user-images.githubusercontent.com/11651596/43074832-e675677c-8e7e-11e8-9a96-ecc7e307fcc4.png)
and crash
![win_bug_1_4](https://user-images.githubusercontent.com/11651596/43074833-e7b56966-8e7e-11e8-9e2b-205065549039.png)

**Comment by StephanJanosch** [comment]
Problem found: If I rename nip2-gfp_his72-mCh_his58-mCh.tif to nip2-gfp_his72-mCh_his58-mCh**0**.tif than the automatic loader works.

It's the code which tries to find the tiles pattern. It does not take into account that the first tile has no number. Renaming the file does not trigger this issue. 

The microscope names these file like this.

**Comment by hoerldavid** [comment]
Hi @StephanJanosch,

exactly, **there needs to be a varying *numeric* pattern** for the auto-detection to work.

Regardless, I will have a look at the files you sent, maybe we can detect the correct information from the ```Fluoview?```  metadata so the files don't have to have a pattern.

Best,
David

**Comment by StephanJanosch** [comment]
Thanks for looking into it @hoerldavid . This problem is not urgent at all. We understood it, we can live with it.

**Comment by jandoG** [comment]
The same issue still exists. However, the tip varying numeric pattern helped 👍 to move forward. Thanks @hoerldavid !

> Hi @StephanJanosch,
> 
> exactly, **there needs to be a varying _numeric_ pattern** for the auto-detection to work.
> 
> Regardless, I will have a look at the files you sent, maybe we can detect the correct information from the `Fluoview?` metadata so the files don't have to have a pattern.
> 
> Best,
> David

**Comment by lacan** [comment]
Hello, 

I am experiencing hte same issue, however I can't really do much about it because this is a bunch of tiles and timepoints inside a LIF file, so I cannot do a renaming trick... The data has 16 tiles, 4 channels, 121 slices and 12 timepoints...

Is there something I can do perhaps on the scope to avoid this problem other than exporting everything as separate TIF? Anz and all advice welcome.
```
VS: 0
Error: more than one View: ch0 a0 ti0 tp0 i0
VS: 0
Error: more than one View: ch0 a0 ti1 tp0 i0
VS: 0
Error: more than one View: ch0 a0 ti2 tp0 i0
VS: 0
Error: more than one View: ch0 a0 ti3 tp0 i0
VS: 0
Error: more than one View: ch0 a0 ti4 tp0 i0
VS: 0
Error: more than one View: ch0 a0 ti5 tp0 i0
VS: 0
Error: more than one View: ch0 a0 ti6 tp0 i0
VS: 0
Error: more than one View: ch0 a0 ti7 tp0 i0
VS: 0
Error: more than one View: ch0 a0 ti8 tp0 i0
VS: 0
Error: more than one View: ch0 a0 ti9 tp0 i0
VS: 0
Error: more than one View: ch0 a0 ti10 tp0 i0
VS: 0
Error: more than one View: ch0 a0 ti11 tp0 i0
VS: 0
Error: more than one View: ch0 a0 ti12 tp0 i0
VS: 0
Error: more than one View: ch0 a0 ti13 tp0 i0
VS: 0
Error: more than one View: ch0 a0 ti14 tp0 i0
VS: 0
Error: more than one View: ch0 a0 ti15 tp0 i0
VS: 0
Error: more than one View: ch1 a0 ti0 tp0 i0
VS: 0
Error: more than one View: ch1 a0 ti1 tp0 i0
VS: 0
Error: more than one View: ch1 a0 ti2 tp0 i0
VS: 0
Error: more than one View: ch1 a0 ti3 tp0 i0
VS: 0
Error: more than one View: ch1 a0 ti4 tp0 i0
VS: 0
Error: more than one View: ch1 a0 ti5 tp0 i0
VS: 0
Error: more than one View: ch1 a0 ti6 tp0 i0
VS: 0
Error: more than one View: ch1 a0 ti7 tp0 i0
VS: 0
Error: more than one View: ch1 a0 ti8 tp0 i0
VS: 0
Error: more than one View: ch1 a0 ti9 tp0 i0
VS: 0
Error: more than one View: ch1 a0 ti10 tp0 i0
VS: 0
Error: more than one View: ch1 a0 ti11 tp0 i0
VS: 0
Error: more than one View: ch1 a0 ti12 tp0 i0
VS: 0
Error: more than one View: ch1 a0 ti13 tp0 i0
VS: 0
Error: more than one View: ch1 a0 ti14 tp0 i0
VS: 0
Error: more than one View: ch1 a0 ti15 tp0 i0
true
[ERROR] Module threw exception
java.util.NoSuchElementException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1444)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1466)
	at net.preibisch.mvrecon.fiji.datasetmanager.FileListDatasetDefinition.createDataset(FileListDatasetDefinition.java:1042)
	at net.preibisch.mvrecon.fiji.plugin.Define_Multi_View_Dataset.defineDataset(Define_Multi_View_Dataset.java:142)
	at net.preibisch.mvrecon.fiji.plugin.queryXML.LoadParseQueryXML.queryXML(LoadParseQueryXML.java:122)
	at net.preibisch.mvrecon.fiji.plugin.queryXML.LoadParseQueryXML.queryXML(LoadParseQueryXML.java:109)
	at net.preibisch.stitcher.plugin.BigStitcher.run(BigStitcher.java:73)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
