### ISSUE TITLE
NullPointerException when cancelling macro-recordable dialog

### ISSUE THREAD

**Issue by imagejan** [PreibischLab/BigStitcher#5]
When choosing the option _Move Tile to Grid (Macro-scriptable)_ in the Define Metadata for Views dialog, then cancelling the following dialog Move Tiles of Angle 0, clicking OK in the following dialog will lead to the following exception:

```
(Fiji Is Just) ImageJ 2.0.0-rc-61/1.51n; Java 1.8.0_66 [64-bit]; Mac OS X 10.12.5; 41MB of 3764MB (1%)
 
java.lang.NullPointerException
	at spim.fiji.datasetmanager.grid.RegularTranformHelpers.generateRegularGrid(RegularTranformHelpers.java:153)
	at spim.fiji.datasetmanager.grid.RegularTranformHelpers.applyToSpimDataSingleTP(RegularTranformHelpers.java:285)
	at spim.fiji.datasetmanager.grid.RegularTranformHelpers.applyToSpimData(RegularTranformHelpers.java:239)
	at spim.fiji.datasetmanager.FileListDatasetDefinition.createDataset(FileListDatasetDefinition.java:1066)
	at spim.fiji.plugin.Define_Multi_View_Dataset.defineDataset(Define_Multi_View_Dataset.java:111)
	at spim.fiji.plugin.queryXML.LoadParseQueryXML.queryXML(LoadParseQueryXML.java:99)
	at spim.fiji.plugin.queryXML.LoadParseQueryXML.queryXML(LoadParseQueryXML.java:86)
	at spim.fiji.plugin.Stitching_Explorer.run(Stitching_Explorer.java:41)
	at ij.IJ.runUserPlugIn(IJ.java:217)
	at ij.IJ.runPlugIn(IJ.java:181)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by StephanPreibisch** [comment]
Thanks, fixed with commit https://github.com/fiji/SPIM_Registration/commit/9759374a48eac9ffec131cf8ec656bc767e495f9
