### ISSUE TITLE
Error creating a bounding box

### ISSUE THREAD

**Issue by lacan** [PreibischLab/BigStitcher#53]
On a fresh Fiji installation with the BigStitcher update site. Everzthing seems to work fine until I want to create a bounding box, where I am met with

```
Exception in thread "Thread-18" java.lang.NoClassDefFoundError: org/scijava/listeners/ListenableVar
	at bdv.tools.boundingbox.TransformedBoxOverlay.<init>(TransformedBoxOverlay.java:110)
	at bdv.tools.boundingbox.BoundingBoxDialog.<init>(BoundingBoxDialog.java:144)
	at bdv.tools.boundingbox.BoundingBoxDialog.<init>(BoundingBoxDialog.java:99)
	at net.preibisch.mvrecon.process.boundingbox.BoundingBoxBigDataViewer$1.<init>(BoundingBoxBigDataViewer.java:123)
	at net.preibisch.mvrecon.process.boundingbox.BoundingBoxBigDataViewer.estimate(BoundingBoxBigDataViewer.java:122)
	at net.preibisch.mvrecon.fiji.plugin.boundingbox.BDVBoundingBoxGUI.setUpDefaultValues(BDVBoundingBoxGUI.java:52)
	at net.preibisch.mvrecon.fiji.plugin.boundingbox.BoundingBoxGUI.getSimpleDialog(BoundingBoxGUI.java:164)
	at net.preibisch.mvrecon.fiji.plugin.boundingbox.BoundingBoxGUI.queryParameters(BoundingBoxGUI.java:96)
	at net.preibisch.mvrecon.fiji.plugin.Define_Bounding_Box.defineBoundingBox(Define_Bounding_Box.java:137)
	at net.preibisch.mvrecon.fiji.plugin.Define_Bounding_Box.defineBoundingBox(Define_Bounding_Box.java:84)
	at net.preibisch.mvrecon.fiji.spimdata.explorer.popup.BoundingBoxPopup$MyActionListener$1.run(BoundingBoxPopup.java:89)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.scijava.listeners.ListenableVar
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 12 more
```

Which dependency am I missing or have the wrong version of?

Thanks for any help

Oli

**Comment by hoerldavid** [comment]
Hi @lacan ,

This is a problem with BigDataViewer, actually. Since Version 7.0.0 it depends on ```scijava-listeners```  (https://github.com/bigdataviewer/bigdataviewer-core/commit/0acbba6753b2dcd0ad31f880464a07e51745f751), which is **NOT** shipped with Fiji, as far as I can tell.

Pinging @tpietzsch since the Problem lies with https://github.com/bigdataviewer/bigdataviewer-core, and @ctrueden since it involves missing dependencies in Fiji.

A solution in the meanwhile would be to clone https://github.com/scijava/scijava-listeners, build it with Maven (```mvn package```) and copy the generated .jar to the ```Fiji.app/jars``` directory. That works for me.

Best,
David

**Comment by tpietzsch** [comment]
@hoerldavid Thanks for pinging! I'll put scijava-listeners on the Fiji update site this afternoon. This should revolve it.

**Comment by hoerldavid** [comment]
I just tested it, works perfectly.
Thanks a lot @tpietzsch 🥇 

@lacan just update your Fiji and you should be good to go!

Best,
David

**Comment by tpietzsch** [comment]
@hoerldavid Wow, good instincts. I just uploaded it like 3 minutes ago :-)

**Comment by lacan** [comment]
Wonderful, thank you so much!
