### ISSUE TITLE
Fuse dataset in --headless_mode results in XmlIoBasicImgLoader-Error

### ISSUE THREAD

**Issue by maxsenh** [PreibischLab/BigStitcher#55]
Servus Preibisch-Lab!

First of all, thank you for BigStitcher, a wonderful program!

In order to automate the processing of my microscopy samples, I am running BigStitcher in Ubuntu 18.04 in the --headless (batch processing) mode. The data consists of microscopy images that were acquired in a z-stacked tile-scan. First, I set the focus for each tile with the program Stack Focuser and then stitched them together with BigStitcher. In --headless mode everything runs smoothely except for the dataset-fusion, the last step, where I would like to save the stitched dataset to a .tiff file. In interactive mode, however, it works without problem and I can save the stitched data set.

In bash:
```bash

java -jar Desktop/Fiji.app/jars/ij-1.52p.jar -ijpath Desktop/Fiji.app -macro stitch $unstitched_dir#$stitch_dir
```

which calls the script stitch.ijm in the macros of Fiji:
```javascript

path_list = getArgument();
paths = split(path_list,'#');

// Dataset definition
run("Define dataset ...", "define_dataset=[Automatic Loader (Bioformats based)] project_filename=dataset.xml path=" + va[0] + " exclude=10 pattern_0=Channels pattern_1=Tiles move_tiles_to_grid_(per_angle)?=[Move Tiles to Grid (interactive)] how_to_load_images=[Re-save as multiresolution HDF5] dataset_save_path=" + paths[0] + " check_stack_sizes subsampling_factors=[{ {1,1,1}, {2,2,2}, {4,4,4}, {8,8,8} }] hdf5_chunk_sizes=[{ {16,16,16}, {16,16,16}, {16,16,16}, {16,16,16} }] timepoints_per_partition=1 setups_per_partition=0 use_deflate_compression export_path=" + paths[0]);

// Pairwise shift calculation
run("Calculate pairwise shifts ...", "select=" + paths[0] + "dataset.xml process_angle=[All angles] process_channel=[All channels] process_illumination=[All illuminations] process_tile=[All tiles] process_timepoint=[All Timepoints] method=[Phase Correlation] channels=[Average Channels] downsample_in_x=2 downsample_in_y=2");

// Filter pairwise shift
run("Filter pairwise shifts ...", "select=" + paths[0] + "dataset.xml min_r=0 max_r=1 max_shift_in_x=0 max_shift_in_y=0 max_shift_in_z=0 max_displacement=0");

// Global optimization
run("Optimize globally and apply shifts ...", "select=" + paths[0] + "dataset.xml process_angle=[All angles] process_channel=[All channels] process_illumination=[All illuminations] process_tile=[All tiles] process_timepoint=[All Timepoints] relative=2.500 absolute=3.500 global_optimization_strategy=[Two-Round using Metadata to align unconnected Tiles] fix_group_0-0,");

// Dataset fusion
run("Fuse dataset ...",
    "select=" + paths[0] + "dataset1.xml process_angle=[All angles] process_channel=[All channels] " +
    "process_illumination=[All illuminations] process_tile=[All tiles] process_timepoint=[All Timepoints]" + 
    " bounding_box=[All Views] downsampling=1 pixel_type=[16-bit unsigned integer] interpolation=[Linear Interpolation]" +
    " image=[Precompute Image] blend produce=[Each timepoint & channel] fused_image=[Save as (compressed) TIFF stacks] " +
    "output_file_directory=" + paths[1]);

// Exit
eval("script", "System.exit(0);");
```

As I said, all the steps work but the data set fusion, where I receive the following error:

```bash
mpicbg.spim.data.SpimDataInstantiationException: could not find XmlIoBasicImgLoader implementation for format bdv.hdf5
	at mpicbg.spim.data.generic.sequence.ImgLoaders.createXmlIoForFormat(ImgLoaders.java:72)
	at mpicbg.spim.data.generic.sequence.XmlIoAbstractSequenceDescription.fromXml(XmlIoAbstractSequenceDescription.java:110)
	at mpicbg.spim.data.generic.XmlIoAbstractSpimData.fromXml(XmlIoAbstractSpimData.java:153)
	at net.preibisch.mvrecon.fiji.spimdata.XmlIoSpimData2.fromXml(XmlIoSpimData2.java:164)
	at net.preibisch.mvrecon.fiji.spimdata.XmlIoSpimData2.fromXml(XmlIoSpimData2.java:52)
	at mpicbg.spim.data.generic.XmlIoAbstractSpimData.load(XmlIoAbstractSpimData.java:95)
	at net.preibisch.mvrecon.fiji.plugin.queryXML.GenericLoadParseQueryXML.parseXML(GenericLoadParseQueryXML.java:942)
	at net.preibisch.mvrecon.fiji.plugin.queryXML.GenericLoadParseQueryXML.tryParsing(GenericLoadParseQueryXML.java:728)
	at net.preibisch.mvrecon.fiji.plugin.queryXML.GenericLoadParseQueryXML.queryXML(GenericLoadParseQueryXML.java:329)
	at net.preibisch.mvrecon.fiji.plugin.queryXML.LoadParseQueryXML.queryXML(LoadParseQueryXML.java:118)
	at net.preibisch.mvrecon.fiji.plugin.queryXML.LoadParseQueryXML.queryXML(LoadParseQueryXML.java:109)
	at net.preibisch.mvrecon.fiji.plugin.queryXML.LoadParseQueryXML.queryXML(LoadParseQueryXML.java:58)
	at net.preibisch.mvrecon.fiji.plugin.Image_Fusion.run(Image_Fusion.java:86)
	at ij.IJ.runUserPlugIn(IJ.java:230)
	at ij.IJ.runPlugIn(IJ.java:193)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at ij.IJ.run(IJ.java:312)
	at ij.IJ.run(IJ.java:323)
	at ij.macro.Functions.doRun(Functions.java:624)
	at ij.macro.Functions.doFunction(Functions.java:97)
	at ij.macro.Interpreter.doStatement(Interpreter.java:275)
	at ij.macro.Interpreter.doStatements(Interpreter.java:261)
	at ij.macro.Interpreter.run(Interpreter.java:157)
	at ij.macro.Interpreter.run(Interpreter.java:91)
	at ij.macro.Interpreter.run(Interpreter.java:102)
	at ij.plugin.Macro_Runner.runMacro(Macro_Runner.java:161)
	at ij.plugin.Macro_Runner.runMacroFile(Macro_Runner.java:145)
	at ij.IJ.runMacroFile(IJ.java:160)
	at ij.ImageJ.main(ImageJ.java:744)
```

Does anyone have an idea what could cause this problem? It seems, some program is not up-to-date, but I updated all BigStitcher and BigDataViewer.

**Comment by davidchenlee** [comment]
Preibisch-Lab!

I have the exact same problem.  My macro runs smoothly on Fiji but the fusion throws the following exception under headless mode. BTW, great software! It will enable me to reconstruct an entire mouse liver (several TBs).

`java.lang.NullPointerException
	at net.preibisch.mvrecon.fiji.plugin.fusion.FusionGUI.queryDetails(FusionGUI.java:218)
	at net.preibisch.mvrecon.fiji.plugin.Image_Fusion.fuse(Image_Fusion.java:98)
	at net.preibisch.mvrecon.fiji.plugin.Image_Fusion.run(Image_Fusion.java:89)
	at ij.IJ.runUserPlugIn(IJ.java:230)
	at ij.IJ.runPlugIn(IJ.java:193)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at ij.IJ.run(IJ.java:312)
	at ij.IJ.run(IJ.java:323)
	at ij.macro.Functions.doRun(Functions.java:624)
	at ij.macro.Functions.doFunction(Functions.java:97)
	at ij.macro.Interpreter.doStatement(Interpreter.java:275)
	at ij.macro.Interpreter.doStatements(Interpreter.java:261)
	at ij.macro.Interpreter.run(Interpreter.java:157)
	at ij.macro.Interpreter.run(Interpreter.java:91)
	at ij.macro.Interpreter.run(Interpreter.java:102)
	at ij.plugin.Macro_Runner.runMacro(Macro_Runner.java:161)
	at ij.plugin.Macro_Runner.runMacroFile(Macro_Runner.java:145)
	at ij.IJ.runMacroFile(IJ.java:160)
	at net.imagej.legacy.IJ1Helper$4.call(IJ1Helper.java:1125)
	at net.imagej.legacy.IJ1Helper$4.call(IJ1Helper.java:1121)
	at net.imagej.legacy.IJ1Helper.runMacroFriendly(IJ1Helper.java:1055)
	at net.imagej.legacy.IJ1Helper.runMacroFile(IJ1Helper.java:1121)
	at net.imagej.legacy.LegacyCommandline$Macro.handle(LegacyCommandline.java:187)
	at org.scijava.console.DefaultConsoleService.processArgs(DefaultConsoleService.java:102)
	at org.scijava.AbstractGateway.launch(AbstractGateway.java:97)
	at net.imagej.Main.main(Main.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.imagej.launcher.ClassLauncher.launch(ClassLauncher.java:279)
	at net.imagej.launcher.ClassLauncher.run(ClassLauncher.java:186)
	at net.imagej.launcher.ClassLauncher.main(ClassLauncher.java:77)
`
