### ISSUE TITLE
Multiview - Resave as TIFF - NullPointerException

### ISSUE THREAD

**Issue by hajaalin** [PreibischLab/BigStitcher#59]
This error is with ImageJ 1.52p, Java_1.8.0_212, and Fiji updated today (2019-10-01).

```
Exception in thread "Thread-15" java.lang.NullPointerException
	at net.preibisch.mvrecon.process.export.Save3dTIFF.getFileName(Save3dTIFF.java:90)
	at net.preibisch.mvrecon.process.export.Save3dTIFF.exportImage(Save3dTIFF.java:129)
	at net.preibisch.mvrecon.process.export.Save3dTIFF.exportImage(Save3dTIFF.java:82)
	at net.preibisch.mvrecon.process.export.Save3dTIFF.exportImage(Save3dTIFF.java:70)
	at net.preibisch.mvrecon.fiji.plugin.resave.Resave_TIFF.writeTIFF(Resave_TIFF.java:260)
	at net.preibisch.mvrecon.fiji.spimdata.explorer.popup.ResavePopup$MyActionListener$1.run(ResavePopup.java:191)
	at java.lang.Thread.run(Thread.java:748)
```
The variable with null value is _fnAddition_, 
https://github.com/PreibischLab/multiview-reconstruction/blob/3fac28bf549114d0ea400d27112bb6922415ae57/src/main/java/net/preibisch/mvrecon/process/export/Save3dTIFF.java#L90
which should get it's value in method _queryParameters_:
https://github.com/PreibischLab/multiview-reconstruction/blob/3fac28bf549114d0ea400d27112bb6922415ae57/src/main/java/net/preibisch/mvrecon/process/export/Save3dTIFF.java#L201

The _queryParameters_ method looks like it should open a dialog, but there was no dialog.

**Comment by hajaalin** [comment]
I get the same error also when opening and trying to resave the same data set with the Multiview Reconstruction plugin.
