### ISSUE TITLE
Can no longer view or save images after deconvolution

### ISSUE THREAD

**Issue by lacan** [PreibischLab/BigStitcher#61]
I am trying to deconvolve some data. I assign the PSF and run the deconvolution. Everything works but at the end I get this error
```
Exception in thread "Thread-10163" java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@2b8f2874 rejected from java.util.concurrent.ThreadPoolExecutor@25660354[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 12]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379)
	at java.util.concurrent.AbstractExecutorService.invokeAll(AbstractExecutorService.java:238)
	at net.imglib2.display.projector.MultithreadedIterableIntervalProjector2D.map(MultithreadedIterableIntervalProjector2D.java:178)
	at net.imglib2.img.display.imagej.ImageJVirtualStack.getSlice(ImageJVirtualStack.java:148)
	at net.imglib2.img.display.imagej.ImageJVirtualStack.getPixelsZeroBasedIndex(ImageJVirtualStack.java:155)
	at net.imglib2.img.display.imagej.AbstractVirtualStack.getPixels(AbstractVirtualStack.java:89)
	at net.imglib2.img.display.imagej.AbstractVirtualStack.getProcessor(AbstractVirtualStack.java:111)
	at ij.io.ImageWriter.writeFloatVirtualStack(ImageWriter.java:200)
	at ij.io.ImageWriter.write(ImageWriter.java:288)
	at ij.io.TiffEncoder.write(TiffEncoder.java:129)
	at ij.io.TiffEncoder.write(TiffEncoder.java:150)
	at net.preibisch.mvrecon.process.export.Save3dTIFF.saveTiffStack(Save3dTIFF.java:164)
	at net.preibisch.mvrecon.process.export.Save3dTIFF.exportImage(Save3dTIFF.java:138)
	at net.preibisch.mvrecon.process.export.Save3dTIFF.exportImage(Save3dTIFF.java:82)
	at net.preibisch.mvrecon.fiji.plugin.Image_Deconvolution.export(Image_Deconvolution.java:296)
	at net.preibisch.mvrecon.fiji.plugin.Image_Deconvolution.deconvolve(Image_Deconvolution.java:260)
	at net.preibisch.mvrecon.fiji.plugin.Image_Deconvolution.deconvolve(Image_Deconvolution.java:89)
	at net.preibisch.mvrecon.fiji.spimdata.explorer.popup.DeconvolutionPopup$MyActionListener$1.run(DeconvolutionPopup.java:82)
	at java.lang.Thread.run(Thread.java:748)
```
This is when setting it to write the data to disk. 

When displaying the data on ImageJ, I get a similar error that says it cannot access the slice when I move the slider...

Any help appreciated. 

These are the setting I used
![decon settings](https://user-images.githubusercontent.com/319932/67567250-da516d00-f729-11e9-8d19-dd3c47c6a3c8.jpg)

**Comment by alonyan** [comment]
I'm getting the same errors. Any ideas anyone?

**Comment by StephanPreibisch** [comment]
Hi, I fixed that some time ago ... can you please confirm that you are running the newest version?

https://github.com/PreibischLab/multiview-reconstruction/commit/b1358a38fb7da84f3269413ea5e77a7ef6acebc9

**Comment by StephanPreibisch** [comment]
The bug was not limited to deconvolution though, so it could be something else. I will check that meanwhile

**Comment by alonyan** [comment]
Version issue. Thank Stephan!

**Comment by StephanPreibisch** [comment]
Great! 😊
