### ISSUE TITLE
Batch Processing -> Fuse -> save as new hdf5 crashes

### ISSUE THREAD

**Issue by martinschorb** [PreibischLab/BigStitcher#70]
Hi Sebastian,

the next step with our favourite dataset...

Fusion works (export to ImageJ window is OK). HDF5 export results in an empty file and:

```
...
View tpId=0 setupId=16 is currently scaled by: (1, 1, 222.7668)
(1.0, 1.0, 222.76677)
testing scale: 3d-affine: (1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0)
(1.0, 1.0, 222.76677) valid: true bestScaling: 1.0
testing scale: 3d-affine: (2.0, 0.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0)
(2.0, 2.0, 222.76677) valid: false bestScaling: 1.0
testing scale: 3d-affine: (4.0, 0.0, 0.0, 0.0, 0.0, 4.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0)
(4.0, 4.0, 222.76677) valid: false bestScaling: 1.0
testing scale: 3d-affine: (8.0, 0.0, 0.0, 0.0, 0.0, 8.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0)
(8.0, 8.0, 222.76677) valid: false bestScaling: 1.0
Choosing resolution level: 1.0 x 1.0 x 1.0
View tpId=0 setupId=17 is currently scaled by: (1, 1, 222.7668)
exportImage2()
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 2
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at bdv.export.ExportScalePyramid.writeScalePyramid(ExportScalePyramid.java:400)
	at bdv.export.WriteSequenceToHdf5.writeViewToHdf5PartitionFile(WriteSequenceToHdf5.java:689)
	at bdv.export.WriteSequenceToHdf5.writeViewToHdf5PartitionFile(WriteSequenceToHdf5.java:536)
	at net.preibisch.mvrecon.process.export.ExportSpimData2HDF5.exportImage(ExportSpimData2HDF5.java:298)
	at net.preibisch.mvrecon.fiji.plugin.Image_Fusion.cacheAndExport(Image_Fusion.java:346)
	at net.preibisch.mvrecon.fiji.plugin.Image_Fusion.fuse(Image_Fusion.java:265)
	at net.preibisch.mvrecon.fiji.plugin.Image_Fusion.run(Image_Fusion.java:89)
	at ij.IJ.runUserPlugIn(IJ.java:230)
	at ij.IJ.runPlugIn(IJ.java:193)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 2
	at net.imglib2.img.planar.PlanarRandomAccess.fwd(PlanarRandomAccess.java:116)
	at bdv.export.DownsampleBlockInstances$Imp.downsampleBlock3D(DownsampleBlock.java:125)
	at bdv.export.DownsampleBlockInstances$Imp.downsampleBlock(DownsampleBlock.java:93)
	at bdv.export.ExportScalePyramid.lambda$writeScalePyramid$0(ExportScalePyramid.java:388)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
java.io.IOException: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 2
	at bdv.export.ExportScalePyramid.writeScalePyramid(ExportScalePyramid.java:406)
	at bdv.export.WriteSequenceToHdf5.writeViewToHdf5PartitionFile(WriteSequenceToHdf5.java:689)
	at bdv.export.WriteSequenceToHdf5.writeViewToHdf5PartitionFile(WriteSequenceToHdf5.java:536)
	at net.preibisch.mvrecon.process.export.ExportSpimData2HDF5.exportImage(ExportSpimData2HDF5.java:298)
	at net.preibisch.mvrecon.fiji.plugin.Image_Fusion.cacheAndExport(Image_Fusion.java:346)
	at net.preibisch.mvrecon.fiji.plugin.Image_Fusion.fuse(Image_Fusion.java:265)
	at net.preibisch.mvrecon.fiji.plugin.Image_Fusion.run(Image_Fusion.java:89)
	at ij.IJ.runUserPlugIn(IJ.java:230)
	at ij.IJ.runPlugIn(IJ.java:193)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 2
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at bdv.export.ExportScalePyramid.writeScalePyramid(ExportScalePyramid.java:400)
	... 11 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 2
	at net.imglib2.img.planar.PlanarRandomAccess.fwd(PlanarRandomAccess.java:116)
	at bdv.export.DownsampleBlockInstances$Imp.downsampleBlock3D(DownsampleBlock.java:125)
	at bdv.export.DownsampleBlockInstances$Imp.downsampleBlock(DownsampleBlock.java:93)
	at bdv.export.ExportScalePyramid.lambda$writeScalePyramid$0(ExportScalePyramid.java:388)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
finish()
```

**Comment by martinschorb** [comment]
When I launch it from BigStitcher's GUI, the error is almost exactly the same:

```
View tpId=0 setupId=17 is currently scaled by: (1, 1, 222.7668)
exportImage2()
java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at bdv.export.ExportScalePyramid.writeScalePyramid(ExportScalePyramid.java:400)
	at bdv.export.WriteSequenceToHdf5.writeViewToHdf5PartitionFile(WriteSequenceToHdf5.java:689)
	at bdv.export.WriteSequenceToHdf5.writeViewToHdf5PartitionFile(WriteSequenceToHdf5.java:536)
	at net.preibisch.mvrecon.process.export.ExportSpimData2HDF5.exportImage(ExportSpimData2HDF5.java:298)
	at net.preibisch.mvrecon.fiji.plugin.Image_Fusion.cacheAndExport(Image_Fusion.java:346)
	at net.preibisch.mvrecon.fiji.plugin.Image_Fusion.fuse(Image_Fusion.java:265)
	at net.preibisch.mvrecon.fiji.spimdata.explorer.popup.FusionPopup$MyActionListener$1.run(FusionPopup.java:82)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ArrayIndexOutOfBoundsException
java.io.IOException: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException
	at bdv.export.ExportScalePyramid.writeScalePyramid(ExportScalePyramid.java:406)
	at bdv.export.WriteSequenceToHdf5.writeViewToHdf5PartitionFile(WriteSequenceToHdf5.java:689)
	at bdv.export.WriteSequenceToHdf5.writeViewToHdf5PartitionFile(WriteSequenceToHdf5.java:536)
	at net.preibisch.mvrecon.process.export.ExportSpimData2HDF5.exportImage(ExportSpimData2HDF5.java:298)
	at net.preibisch.mvrecon.fiji.plugin.Image_Fusion.cacheAndExport(Image_Fusion.java:346)
	at net.preibisch.mvrecon.fiji.plugin.Image_Fusion.fuse(Image_Fusion.java:265)
	at net.preibisch.mvrecon.fiji.spimdata.explorer.popup.FusionPopup$MyActionListener$1.run(FusionPopup.java:82)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at bdv.export.ExportScalePyramid.writeScalePyramid(ExportScalePyramid.java:400)
	... 7 more
Caused by: java.lang.ArrayIndexOutOfBoundsException
finish()
```

here' s the incomplete h5 files. This time no Windows path separator problem...
[dataset001-f1.zip](https://github.com/PreibischLab/BigStitcher/files/4380409/dataset001-f1.zip)
