### ISSUE TITLE
NoClassDefFoundError: StopWatch

### ISSUE THREAD

**Issue by haesleinhuepf** [PreibischLab/BigStitcher#75]
Hi @StephanPreibisch, @hoerldavid et al.,

I was just playing with BigStitcher for teaching purposes. While resaving the [Grid3D](http://preibischlab.mdc-berlin.de/BigStitcher/Grid_3d.zip) example from the [wiki page](https://imagej.net/BigStitcher), I retrieved an error message (see below). I'm running in a freshly downloaded Fiji, where only clij,clij2 and BigStitcher update sites are activated.

I can continue working with the raw data, so no hurry. Let me know if I can help tracing down this bug.

Cheers,
Robert

```
(Fiji Is Just) ImageJ 2.0.0-rc-72/1.52p; Java 1.8.0_172 [64-bit]; Windows 10 10.0; 80MB of 12033MB (<1%)
 
java.lang.NoClassDefFoundError: org/perf4j/StopWatch
	at net.preibisch.mvrecon.fiji.spimdata.imgloaders.LegacyFileMapImgLoaderLOCI.openImg(LegacyFileMapImgLoaderLOCI.java:205)
	at net.preibisch.mvrecon.fiji.spimdata.imgloaders.LegacyFileMapImgLoaderLOCI.getImage(LegacyFileMapImgLoaderLOCI.java:158)
	at mpicbg.spim.data.legacy.LegacyImgLoaderWrapper$SetupImgLoaderWrapper.getImage(LegacyImgLoaderWrapper.java:79)
	at bdv.export.WriteSequenceToHdf5.writeHdf5PartitionFile(WriteSequenceToHdf5.java:446)
	at bdv.export.WriteSequenceToHdf5.writeHdf5File(WriteSequenceToHdf5.java:153)
	at net.preibisch.mvrecon.fiji.plugin.resave.Generic_Resave_HDF5.writeHDF5(Generic_Resave_HDF5.java:261)
	at net.preibisch.mvrecon.fiji.datasetmanager.FileListDatasetDefinition.createDataset(FileListDatasetDefinition.java:1147)
	at net.preibisch.mvrecon.fiji.plugin.Define_Multi_View_Dataset.defineDataset(Define_Multi_View_Dataset.java:142)
	at net.preibisch.mvrecon.fiji.plugin.Define_Multi_View_Dataset.run(Define_Multi_View_Dataset.java:80)
	at ij.IJ.runUserPlugIn(IJ.java:230)
	at ij.IJ.runPlugIn(IJ.java:193)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.perf4j.StopWatch
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 14 more
```

**Comment by haesleinhuepf** [comment]
Addendum: Similar error pops up later when trying to view something in the BigDataViewer:

```
WARNING:
Opening <SpimData> dataset that is not suited for interactive browsing.
Consider resaving as HDF5 for better performance.
Exception in thread "PainterThread" java.lang.NoClassDefFoundError: org/perf4j/StopWatch
	at net.preibisch.mvrecon.fiji.spimdata.imgloaders.LegacyFileMapImgLoaderLOCI.openImg(LegacyFileMapImgLoaderLOCI.java:205)
	at net.preibisch.mvrecon.fiji.spimdata.imgloaders.LegacyFileMapImgLoaderLOCI.getImage(LegacyFileMapImgLoaderLOCI.java:158)
	at mpicbg.spim.data.legacy.LegacyImgLoaderWrapper$SetupImgLoaderWrapper.getImage(LegacyImgLoaderWrapper.java:79)
	at bdv.spimdata.WrapBasicImgLoader$WrapSetupImgLoader.getImage(WrapBasicImgLoader.java:144)
	at bdv.SpimSource.getImage(SpimSource.java:60)
	at bdv.AbstractSpimSource.lambda$new$0(AbstractSpimSource.java:164)
	at net.imglib2.cache.ref.WeakRefLoaderCache.get(WeakRefLoaderCache.java:102)
	at net.imglib2.cache.ref.BoundedSoftRefLoaderCache.get(BoundedSoftRefLoaderCache.java:54)
	at net.imglib2.cache.util.LoaderCacheAsCacheAdapter.get(LoaderCacheAsCacheAdapter.java:43)
	at net.imglib2.cache.util.CacheAsUncheckedCacheAdapter.get(CacheAsUncheckedCacheAdapter.java:41)
	at bdv.AbstractSpimSource.getSource(AbstractSpimSource.java:231)
	at bdv.AbstractSpimSource.getSource(AbstractSpimSource.java:223)
	at bdv.tools.transformation.TransformedSource.getSource(TransformedSource.java:219)
	at bdv.viewer.render.MultiResolutionRenderer.getTransformedSource(MultiResolutionRenderer.java:788)
	at bdv.viewer.render.MultiResolutionRenderer.createSingleSourceProjector(MultiResolutionRenderer.java:732)
	at bdv.viewer.render.MultiResolutionRenderer.createProjector(MultiResolutionRenderer.java:652)
	at bdv.viewer.render.MultiResolutionRenderer.paint(MultiResolutionRenderer.java:511)
	at bdv.viewer.ViewerPanel.paint(ViewerPanel.java:483)
	at net.imglib2.ui.PainterThread.run(PainterThread.java:86)
Caused by: java.lang.ClassNotFoundException: org.perf4j.StopWatch
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 19 more
Exception in thread "Thread-7" java.lang.NoClassDefFoundError: org/perf4j/StopWatch
	at net.preibisch.mvrecon.fiji.spimdata.imgloaders.LegacyFileMapImgLoaderLOCI.openImg(LegacyFileMapImgLoaderLOCI.java:205)
	at net.preibisch.mvrecon.fiji.spimdata.imgloaders.LegacyFileMapImgLoaderLOCI.getImage(LegacyFileMapImgLoaderLOCI.java:158)
	at mpicbg.spim.data.legacy.LegacyImgLoaderWrapper$SetupImgLoaderWrapper.getImage(LegacyImgLoaderWrapper.java:79)
	at bdv.spimdata.WrapBasicImgLoader$WrapSetupImgLoader.getImage(WrapBasicImgLoader.java:144)
	at bdv.SpimSource.getImage(SpimSource.java:60)
	at bdv.AbstractSpimSource.lambda$new$0(AbstractSpimSource.java:164)
	at net.imglib2.cache.ref.WeakRefLoaderCache.get(WeakRefLoaderCache.java:102)
	at net.imglib2.cache.ref.BoundedSoftRefLoaderCache.get(BoundedSoftRefLoaderCache.java:54)
	at net.imglib2.cache.util.LoaderCacheAsCacheAdapter.get(LoaderCacheAsCacheAdapter.java:43)
	at net.imglib2.cache.util.CacheAsUncheckedCacheAdapter.get(CacheAsUncheckedCacheAdapter.java:41)
	at bdv.AbstractSpimSource.getSource(AbstractSpimSource.java:231)
	at bdv.AbstractSpimSource.getSource(AbstractSpimSource.java:223)
	at bdv.tools.transformation.TransformedSource.getSource(TransformedSource.java:219)
	at bdv.tools.InitializeViewerState.initTransform(InitializeViewerState.java:119)
	at bdv.tools.InitializeViewerState.initTransform(InitializeViewerState.java:80)
	at bdv.BigDataViewer.open(BigDataViewer.java:496)
	at net.preibisch.mvrecon.fiji.spimdata.explorer.popup.BDVPopup.createBDV(BDVPopup.java:295)
	at net.preibisch.mvrecon.fiji.spimdata.explorer.popup.BDVPopup.createBDV(BDVPopup.java:270)
	at net.preibisch.mvrecon.fiji.spimdata.explorer.popup.BDVPopup$MyActionListener$1.run(BDVPopup.java:112)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by haesleinhuepf** [comment]
Was able to make it run by downloading this jar and putting it in Fiji:

https://mvnrepository.com/artifact/org.perf4j/perf4j/0.9.16

I assume it's just missing on the update site?!

Cheers,
Robert

**Comment by StephanPreibisch** [comment]
Hi, I cannot reproduce that error. When exactly do you get it?

**Comment by StephanPreibisch** [comment]
Also, I have the perf4f jar in my Fiji. Did you maybe remove it on your update site?
-rw-r--r--@   1 spreibi  admin    110019 Oct 11  2017 perf4j-0.9.13.jar

**Comment by StephanPreibisch** [comment]
Oh, this is worse, I just clicked Update and it is being uninstalled from the ImageJ update site. @ctrueden do you know anything about it. Seems that BigDataViewer is using it. Also calling @tpietzsch here ...

<img width="892" alt="Screen Shot 2020-06-28 at 2 26 12 PM" src="https://user-images.githubusercontent.com/1420587/85955271-6405aa00-b94b-11ea-83d1-359fe9f83a73.png">

**Comment by StephanPreibisch** [comment]
In BigStitcher we have it as a transitive dependency from formats-bsd ... 
<img width="480" alt="Screen Shot 2020-06-28 at 2 28 49 PM" src="https://user-images.githubusercontent.com/1420587/85955329-c6f74100-b94b-11ea-9bad-5b3cde9a7135.png">

**Comment by haesleinhuepf** [comment]
Maybe it's related to the (currently) broken Fiji update site? See details:
https://forum.image.sc/t/error-could-not-update-from-site-fiji/39611

Btw. you can reproduce the bug by installing bigstitcher to a freshly downloaded Fiji and then converting your Grid 3D Example data set in HDF5 like shown in this video:
![bigstitcher_crash-28-06-2020-20-27-24](https://user-images.githubusercontent.com/12660498/85955414-af857b80-b97e-11ea-8419-b79d3d449d5f.gif)

**Comment by haesleinhuepf** [comment]
Ok, the problem is solved. I assume it was related to the broken Fiji update site. I just tried again with a freshly downloaded Fiji and it's fine now.
Thanks for listening! ;-)

**Comment by StephanPreibisch** [comment]
Thanks so much for reporting it! Was simply bad timing I guess :)
