### ISSUE TITLE
java.lang.NoClassDefFoundError: net/imglib2/converter/BiConverter

### ISSUE THREAD

**Issue by lacan** [PreibischLab/BigStitcher#78]
In an Up-To-Date Fiji the following error occurs when running Interest Point Detection

 ```
Exception in thread "Thread-10740" java.lang.NoClassDefFoundError: net/imglib2/converter/BiConverter
	at net.preibisch.mvrecon.process.interestpointdetection.methods.dog.DoG.addInterestPoints(DoG.java:159)
	at net.preibisch.mvrecon.fiji.plugin.interestpointdetection.DifferenceOfGaussianGUI.findInterestPoints(DifferenceOfGaussianGUI.java:143)
	at net.preibisch.mvrecon.fiji.plugin.Interest_Point_Detection.detectInterestPoints(Interest_Point_Detection.java:215)
	at net.preibisch.mvrecon.fiji.plugin.Interest_Point_Detection.detectInterestPoints(Interest_Point_Detection.java:109)
	at net.preibisch.mvrecon.fiji.spimdata.explorer.popup.DetectInterestPointsPopup$MyActionListener$1.run(DetectInterestPointsPopup.java:87)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.imglib2.converter.BiConverter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 6 more
```

Probably linked to the big update to Fiji that happened recently?

Best

Oli

**Comment by lacan** [comment]
Hmmm, this actually is linked to a difference in dependencies between BDV Playground and BigStitcher actually. Disabling BDV Playground fixes the issue, but it's not an ideal solution....
https://github.com/bigdataviewer/bigdataviewer-playground

**Comment by StephanPreibisch** [comment]
Hi, that means that bigdataviewer-playground uses an older version of imglib2-core than the main Fiji distribution (I assume 5.9.0). It should not use an older version than is shipped with the main Fiji. Who could fix that?
