### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by saskra** [PreibischLab/BigStitcher#84]
I have a dataset of 2048 x 2048 pixels in 4 x 4 tiles with 3 channels and 132 z slices. Unfortunately, the stitching process crashes with this error message:

```java
(Fiji Is Just) ImageJ 2.1.0/1.53c; Java 1.8.0_172 [64-bit]; Linux 4.15.0-124-generic; 281MB of 242549MB (<1%)
 
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:307)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:166)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:150)
	at ij.Executer.run(Executer.java:68)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:303)
	... 5 more
Caused by: java.lang.NullPointerException
	at loci.formats.FileStitcher.setAxisTypes(FileStitcher.java:223)
	at net.preibisch.mvrecon.fiji.spimdata.imgloaders.LegacyFileMapImgLoaderLOCI.lambda$checkAndRemoveZeroVolume$3(LegacyFileMapImgLoaderLOCI.java:488)
	at java.util.HashMap$EntrySet.forEach(HashMap.java:1044)
	at net.preibisch.mvrecon.fiji.spimdata.imgloaders.LegacyFileMapImgLoaderLOCI.checkAndRemoveZeroVolume(LegacyFileMapImgLoaderLOCI.java:472)
	at net.preibisch.mvrecon.fiji.datasetmanager.FileListDatasetDefinition.createDataset(FileListDatasetDefinition.java:1088)
	at net.preibisch.mvrecon.fiji.plugin.Define_Multi_View_Dataset.defineDataset(Define_Multi_View_Dataset.java:142)
	at net.preibisch.mvrecon.fiji.plugin.queryXML.LoadParseQueryXML.queryXML(LoadParseQueryXML.java:122)
	at net.preibisch.mvrecon.fiji.plugin.queryXML.LoadParseQueryXML.queryXML(LoadParseQueryXML.java:109)
	at net.preibisch.stitcher.plugin.BigStitcher.run(BigStitcher.java:73)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
```

Here is the log file:
[Log.txt](https://github.com/PreibischLab/BigStitcher/files/5628555/Log.txt)

Is it because z stacks  are still experimental?

**Comment by StephanPreibisch** [comment]
Hi, I think so ... @hoerldavid do you maybe know more about this?

**Comment by hoerldavid** [comment]
Hi @saskra ,

Just to get it right: the error happens during Dataset definition, correct?
looking at the log, it seems very similar to #85 . Does your fix from there (saving as a single stack file) also work for this?

Regardless, could you send us screenshots of what you selected in the dataset definition dialogs so we can narrow the problem down?
