### ISSUE TITLE
Saving selected views as new HDF5 file fails

### ISSUE THREAD

**Issue by nvladimus** [PreibischLab/BigStitcher#93]
Hi, 
I tried to save selected views as new H5 project by clicking Resave > As HDF5, BigStitcher prompts me to extend selection to all views, I click No and get the following error:
```
Exception in thread "Thread-10" java.lang.NullPointerException
    at net.preibisch.mvrecon.fiji.spimdata.explorer.popup.ResavePopup$MyActionListener$1.run(ResavePopup.java:248)
    at java.lang.Thread.run(Thread.java:748)
```
Thank you!

**Comment by StephanPreibisch** [comment]
Thanks so much @nvladimus. Should be fixed with https://github.com/PreibischLab/multiview-reconstruction/commit/00e9e5bd70cad92604fe266f8e0a92310ab5be81. It is already uploaded to the Fiji Update Site.

**Comment by nvladimus** [comment]
Fixed, many thanks for the quick fix!
